name: mud_thing
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0-70.0.dev

# Add regular dependencies here.
dependencies:
  json_annotation: ^4.9.0
  uuid: ^4.5.1
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  lints: ^5.0.0
  test: ^1.24.0
